# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
         ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\Member:
            algorithm: bcrypt


    providers:
        chain_provider:
             chain:
                providers:
                   - in_memory
                   - db_provider
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$ErnNlWpRapB9ZPjdTHYtcu8I3XbOJqqLwYUehjnf05McbzXR6JWQ6
                        roles: 'ROLE_ADMIN'
        db_provider:
            entity:
                class: AppBundle:Member
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           pattern: ^/
           provider: chain_provider
           form_login:
               login_path: login
               check_path: login
               success_handler: crv.authentication_success_handler
               failure_handler: crv.authentication_failure_handler
           logout: true
           anonymous: ~

    access_control:
        - { path: ^/registration-form-submission$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
